apiVersion: firewall.vyos.crossplane.io/v1alpha1
kind: Ruleset
metadata:
  name: ruleset-a
spec:
  forProvider:
    vyosUrl: "https://10.7.191.156"
    rules:
    - ruleNumber: 2505
      protocol: "tcp"
      action: "accept"
      destination:
        address: "5.5.5.5"
        port: 80
    - ruleNumber: 2506
      protocol: "tcp"
      action: "accept"
      destination:
        address: "5.5.5.5"
        port: 443
  providerConfigRef:
    name: default