apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vyos-composition-firewall
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: VyOSClusterFirewall
  resources:

  - name: ruleset-vyos-primary
    base:
      apiVersion: firewall.vyos.crossplane.io/v1alpha1
      kind: Ruleset
      spec:
        forProvider:
          rules: []
          vyosUrl: ""
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.rules"
      toFieldPath: "spec.forProvider.rules"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.vyosNodes.primarynode.url"
      toFieldPath: "spec.forProvider.vyosUrl"
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: metadata.name
          - fromFieldPath: spec.vyosNodes.primarynode.name
        strategy: string
        string:
          fmt: "%s-%s-rules"
      toFieldPath: metadata.name

  - name: ruleset-vyos-secondary
    base:
      apiVersion: firewall.vyos.crossplane.io/v1alpha1
      kind: Ruleset
      spec:
        forProvider:
          rules: []
          vyosUrl: ""
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.rules"
      toFieldPath: "spec.forProvider.rules"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.vyosNodes.secondarynode.url"
      toFieldPath: "spec.forProvider.vyosUrl"
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: metadata.name
          - fromFieldPath: spec.vyosNodes.secondarynode.name
        strategy: string
        string:
          fmt: "%s-%s-rules"
      toFieldPath: metadata.name


  - name: addtoaddressgroup-vyos-primary
    base:
      apiVersion: firewall.vyos.crossplane.io/v1alpha1
      kind: AddToAddressGroup
      spec:
        forProvider:
          vyosUrl: ""
          ipAddress: ""
          addressGroups: []
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.vyosNodes.primarynode.url"
      toFieldPath: "spec.forProvider.vyosUrl"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.addToAddressGroup.ipAddress"
      toFieldPath: "spec.forProvider.ipAddress"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.addToAddressGroup.addressGroups"
      toFieldPath: "spec.forProvider.addressGroups"
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: metadata.name
          - fromFieldPath: spec.vyosNodes.primarynode.name
        strategy: string
        string:
          fmt: "%s-%s-addtoaddressgroup"
      toFieldPath: metadata.name

  - name: addtoaddressgroup-vyos-secondary
    base:
      apiVersion: firewall.vyos.crossplane.io/v1alpha1
      kind: AddToAddressGroup
      spec:
        forProvider:
          vyosUrl: ""
          ipAddress: ""
          addressGroups: []
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.vyosNodes.secondarynode.url"
      toFieldPath: "spec.forProvider.vyosUrl"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.addToAddressGroup.ipAddress"
      toFieldPath: "spec.forProvider.ipAddress"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.addToAddressGroup.addressGroups"
      toFieldPath: "spec.forProvider.addressGroups"
    - type: CombineFromComposite
      combine:
        variables:
          - fromFieldPath: metadata.name
          - fromFieldPath: spec.vyosNodes.secondarynode.name
        strategy: string
        string:
          fmt: "%s-%s-addtoaddressgroup"
      toFieldPath: metadata.name

  