apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-vyos
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/janorga/provider-vyos
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A vyos that can be used to create Crossplane providers.
